### ISSUE TITLE
签名在固定时间会失败

### ISSUE THREAD

**Issue by zjgtndf** [TencentCloud/tencentcloud-demo-mp-soe#3]
每天刚过0点签名就会失败
一觉睡起来签名又成功了
这是什么情况？

在node端做的验证

**Comment by zqfan** [comment]
没有按照utc转换日期，导致0点到8点期间会固定失败

**Comment by zjgtndf** [comment]
> 没有按照utc转换日期，导致0点到8点期间会固定失败

感谢，重新看了文档，感觉应该是这个原因

**Comment by zqfan** [comment]
> > 没有按照utc转换日期，导致0点到8点期间会固定失败
> 
> 感谢，重新看了文档，感觉应该是这个原因

应该是https://github.com/TencentCloud/tencentcloud-demo-mp-soe/blob/master/node-demo/authorization.js#L37 这里的原因，提个pr吧

**Comment by zjgtndf** [comment]
> > > 没有按照utc转换日期，导致0点到8点期间会固定失败
> > 
> > 
> > 感谢，重新看了文档，感觉应该是这个原因
> 
> 应该是https://github.com/TencentCloud/tencentcloud-demo-mp-soe/blob/master/node-demo/authorization.js#L37 这里的原因，提个pr吧

好的👌
